name: Deploy the react project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t thomaseidg/d-pro -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true thomaseidg/d-pro npm run test

      - name: Tag Docker image
        run: docker tag thomaseidg/d-pro thomaseidg/d-pro:latest

      - name: Push Docker image to Docker Hub
        run: docker push thomaseidg/d-pro:latest
